### ISSUE TITLE
an error please help~~

### ISSUE THREAD

**Issue by destructive-observer** [Jamie725/SRCNN-Pytorch#3]
An error when i was using the python srcnn_main.py ,did you know what's the problem?thank you so much.
Pytorch-master/srcnn_main.py
Traceback (most recent call last):
  File "/home/wc/pytorch_source/SRCNN-Pytorch-master/srcnn_main.py", line 4, in <module>
    from srcnn_module import SRCNN
  File "/home/wc/pytorch_source/SRCNN-Pytorch-master/srcnn_module.py", line 2, in <module>
    import torch.nn as nn
  File "/home/wc/anaconda3/envs/pytorch_conda9.2/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/wc/anaconda3/envs/pytorch_conda9.2/lib/python3.7/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/wc/anaconda3/envs/pytorch_conda9.2/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/wc/anaconda3/lib/libmkl_gnu_thread.so: undefined symbol: mkl_graph_mxm_plus_times_int32_dot_def_i64_i64_i32

**Comment by jiabeiwangTJU** [comment]
hello, did you solve that
